In [11]:
import pandas as pd
from matplotlib.pyplot import *
import sys
sys.path.insert(1,"../../")
from OVTests import *

In [45]:
stock = "AMBUJACEM"
options = []
prices = []

for i in range(7):
    options.append("%s-options-CE-%s.csv"%(stock,str(i+1)))
    prices.append("%s-prices-%s.csv"%(stock,str(i+1)))

In [46]:
tmp = OVBacktest(options[6],prices[6])
df = tmp.options
df.head()

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,...,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value,Delta,OV,OV-Change,OV-Mean,Change,Ratio
0,AMBUJACEM,01-Jul-2022,28-Jul-2022,CE,360,7.30,12.15,7.10,10.80,10.95,...,330.86,775800,52200,-,27,18.875000,0.000000,0.000000,47.945205,0.000000
1,AMBUJACEM,04-Jul-2022,28-Jul-2022,CE,360,11.65,12.20,10.25,11.65,11.45,...,111.61,655200,-120600,-,24,17.613734,-7.160697,0.000000,0.000000,0.000000
2,AMBUJACEM,05-Jul-2022,28-Jul-2022,CE,360,11.00,13.20,9.60,9.75,9.65,...,172.83,628200,-27000,-,23,15.687179,-12.281076,0.000000,-11.363636,0.000000
3,AMBUJACEM,06-Jul-2022,28-Jul-2022,CE,360,10.15,11.80,10.15,10.65,10.50,...,57.44,549000,-79200,368.25,22,17.042254,7.951261,17.391971,4.926108,0.979892

In [44]:
tmp = OVBacktest(options[6],prices[6])
df = tmp.options
df.head()

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,...,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value,Delta,OV,OV-Change,OV-Mean,Change,Ratio
0,AMBUJACEM,01-Jul-2022,28-Jul-2022,PE,360,4.00,4.45,2.30,3.00,2.95,...,86.20,2417400,320400,-,27,67.950000,0.000000,0.000000,-25.000000,0.00000
1,AMBUJACEM,04-Jul-2022,28-Jul-2022,PE,360,3.15,3.35,2.25,2.75,2.90,...,66.80,3108600,691200,-,24,74.618182,8.936404,0.000000,-12.698413,0.00000
2,AMBUJACEM,05-Jul-2022,28-Jul-2022,PE,360,2.90,2.90,1.85,2.40,2.55,...,46.19,3468600,360000,-,23,63.729167,-17.086392,0.000000,-17.241379,0.00000
3,AMBUJACEM,06-Jul-2022,28-Jul-2022,PE,360,3.60,4.00,0.75,0.95,0.85,...,63.30,3645000,176400,368.25,22,191.052632,66.643136,68.765783,-73.611111,2.77831

In [33]:
for i in prices:
    df = pd.read_csv(i)
    df["Close"] = df["Close Price"]
    df["Open"] = df["Open Price"]
    df.to_csv(i)

In [39]:
loader = Loader(options,prices,strategy=2)

In [40]:
loader.find_net_returns(0.3,verbose=True)

Returns: 32.547699214365885
Returns: 40.42261904761905
Returns: 64.60722609986847
Returns: 0
Returns: 3.799311734094317
Returns: 12.721342031686863

154.09819812763462

In [6]:
loader.generate_results(0.3)

In [42]:
loader.find_optimal_threshold(verbose=True)

Max Returns: 631.2752229120262
Optimal Threshold: 0.8900000000000006
Time Taken: 5.476348161697388 seconds

0.8900000000000006